providers:
  docker:
    network: traefik_v2
    exposedByDefault: false
    swarmMode: true
  file:
    watch: true
    filename: /etc/traefik/dynamic-config.yaml
log:
  level: WARN
  format: json
accessLog:
  bufferingSize: 0
  format: json
ping:
  entryPoint: admin
api:
  dashboard: true
  insecure: true
entryPoints:
  metrics:
    address: ":8002"
  admin:
    address: ":8000"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          scheme: https
          to: https
          permanent: true
  https:
    address: ":443"
    http:
      tls:
        options: default
