defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/certificate.crt"
      KeyFile = "/run/secrets/secret.key"

[accessLog]
format = "json"